name: Fast Arch Builder
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y bsdtar wget

      - name: Build Image
        run: |
          # Use the script you already have in the repo
          chmod +x ./archlinux-arm-img/build-arch-arm-img.sh
          sudo ./archlinux-arm-img/build-arch-arm-img.sh ArchLinuxARM-rpi-aarch64-latest.tar.gz

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: arch-rpi-image
          path: archlinux-arm-img/images/*.img
